### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by BOOOO0** [BOOOO0/architecture#4]
#Todo
- [x] 스프링 프로젝트 생성
- [x] MySQL 데이터베이스 연동
- [x] 동작 확인을 위해 입력의 저장과 조회를 위한 api 구현
